version: "0.5"

# TUIの設定
log_location: /tmp/process-compose-${UNAME}.log
log_level: info

processes:
  # ダミープロセス: process-compose の動作確認用
  # リソース消費ゼロで永続的に動作
  dummy-watcher:
    command: "tail -f /dev/null"
    working_dir: "/home/${UNAME}/${REPO_NAME}"
    availability:
      restart: "always"
    environment:
      - HOME=/home/${UNAME}

  # 実験的なサービスの例
  # vite-preview:
  #   command: "npm run preview"
  #   working_dir: "/home/${UNAME}/repos/some-project"
  #   availability:
  #     restart: "no"
  #   depends_on:
  #     difit:
  #       condition: process_started

  # アプリケーションサーバーの例
  # app-server:
  #   command: "npm run dev"
  #   working_dir: "/home/${UNAME}/repos/product-a"
  #   availability:
  #     restart: "no"
  #   environment:
  #     - HOME=/home/${UNAME}
  #     - PORT=8080